# 2.2 - Web Scraping (bs4)

$$$$

![scraping](img/scraping.png)

$$$$

Web scraping o raspado web, es una técnica utilizada mediante programas de software para extraer información de sitios web. Usualmente, estos programas simulan la navegación de un humano en la web ya sea utilizando el protocolo HTTP manualmente, o incrustando un navegador en una aplicación.

El web scraping está muy relacionado con la indexación de la web, la cual indexa la información de la web utilizando un robot y es una técnica universal adoptada por la mayoría de los motores de búsqueda. Sin embargo, el web scraping se enfoca más en la transformación de datos sin estructura en la web, como el formato HTML, en datos estructurados que pueden ser almacenados y analizados en una base de datos central, en una hoja de cálculo o en alguna otra fuente de almacenamiento. Alguno de los usos del web scraping son la comparación de precios en tiendas, la monitorización de datos relacionados con el clima de cierta región, la detección de cambios en sitios webs y la integración de datos en sitios webs. 

En los últimos años el web scraping se ha convertido en una técnica muy utilizada dentro del sector del posicionamiento web gracias a su capacidad de generar grandes cantidades de datos para crear contenidos de calidad.

Podríamos pensar que el web scraping es nuestro último recurso a falta de una API o un feed RSS. A falta de una fuente de datos, siempre podemos extraer aquello que sale por pantalla.

# h1

## h2

### h3

### Extracción desde el HTML

Para scrapear una página web, en primer lugar debemos conocer las estructura que tiene el HTML. Veamos la estructura básica.

El HTML consiste en contenido `<etiquetado>`, es como si fueran cajas de contenido, organizado de manera jerárquica:

```
<html>
    <head>
        <title>Titulo de la pagina</title>
    </head>
    <body>
        <h1>Cabecera</h1>
        <p>Parrafo</p>
    </body>
</html>
```

$$$$

Las etiquetas el HTML se pueden clasificar en varios grupos, dependiendo del tipo de contenido que posea. Estos son algunos ejemplos:

+ cabecera: `<h1>`, `<h2>`, `<h3>`, `<hgroup>`...
+ texto: `<b>`, `<p>`...
+ embebido: `<audio>`, `<img>`, `<video>`...
+ tabular: `<table>`, `<tr>`, `<td>`, `<tbody>`...
+ secciones: `<header>`, `<section>`, `<article>`...
+ metadata: `<meta>`, `<title>`, `<script>`...

$$$$

Las etiquetas pueden tener atributos. Por ejemplo:
 
`<div class="text-monospace" id="name_132", href="www.example.com"> Contenido de la pagina </div>` 

Esta etiqueta `div` tiene los siguientes atributos:

+ class: atributo con valor "text-monospace". La clase no es única en la página.
+ id: atributo con valor "name_132". El id de una etiqueta la identifica de manera unívoca.
+ href: atributo con valor "www.example.com". El href suele contener el link a otra parte de la página.

Siguiendo con la analogía de las cajas, si una etiqueta de HTML es una caja, los atributos serían las pegatinas pegadas en la tapa de la caja.

Conociendo cual es el contenido que queremos extraer, debemos encontrar las etiquetas dentro del HTML de la página web.

Usaremos la herramienta **[BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)**.

In [ ]:
%pip install beautifulsoup4

In [1]:
import requests as req

from bs4 import BeautifulSoup as bs    # ambos alias son cosa mia

### Ejemplos Wikipedia

**[Países europeos según esperanza de vida](https://en.wikipedia.org/wiki/List_of_European_countries_by_life_expectancy)**

In [2]:
url = 'https://en.wikipedia.org/wiki/List_of_European_countries_by_life_expectancy'

In [4]:
# usamos requests para extraer el html

html = req.get(url).text

html[:1000]

'<!DOCTYPE html>\n<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-sticky-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-0 vector-feature-client-preferences-disabled vector-feature-client-prefs-pinned-disabled vector-feature-night-mode-disabled skin-night-mode-clientpref-0 vector-toc-available" lang="en" dir="ltr">\n<head>\n<meta charset="UTF-8">\n<title>List of European countries by life expectancy - Wikipedia</title>\n<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-sticky-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-m'

In [5]:
type(html)

str

In [6]:
'table' in html

True

In [7]:
len(html)

462090

In [9]:
# parsear (traducir string a algo similar al html)

# 'html.parser' esto siempre es igual


sopa = bs(html, 'html.parser')

type(sopa)

bs4.BeautifulSoup

In [12]:
#help(sopa)

In [19]:
sopa.find('table').text.split('\n')[60:80]

['',
 '',
 '',
 '\xa0Liechtenstein',
 '84.40',
 '82.50',
 '86.40',
 '3.90',
 '76.83',
 '5.25',
 '82.07',
 '2.09',
 '84.16',
 '−2.50',
 '81.66',
 '2.74',
 '84.40',
 '0.24',
 '2.33',
 '']

In [20]:
tabla = sopa.find('table')

type(tabla)

bs4.element.Tag

In [24]:
cuerpo = tabla.find('tbody')

In [30]:
# 'tr' = table row, la fila

fila = cuerpo.find_all('tr')[3]

fila

<tr>
<td align="left"><span class="flagicon" style="display:inline-block;width:25px;"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="1000" decoding="async" height="14" src="//upload.wikimedia.org/wikipedia/commons/thumb/4/47/Flag_of_Liechtenstein.svg/23px-Flag_of_Liechtenstein.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/4/47/Flag_of_Liechtenstein.svg/35px-Flag_of_Liechtenstein.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/4/47/Flag_of_Liechtenstein.svg/46px-Flag_of_Liechtenstein.svg.png 2x" width="23"/></span></span></span> <a href="/wiki/Liechtenstein" title="Liechtenstein">Liechtenstein</a></td>
<td style="text-align:center; background:#e0ffd8;">84.40</td>
<td style="text-align:center; background:#eaf3ff;">82.50</td>
<td style="text-align:center; background:#fee7f6;">86.40</td>
<td style="text-align:center; background:#fff8dc;">3.90</td>
<td style="text-align:center; border-left-width:2px; padding-left:1em;">76.83</td>
<td style="background:#fffae0; color:darkgreen;">5.25</td>
<td style="text-align:center;">82.07</td>
<td style="background:#fffae0; color:darkgreen;">2.09</td>
<td style="text-align:center;">84.16</td>
<td style="background:#fffae0; color:crimson;">−2.50</td>
<td style="text-align:center;">81.66</td>
<td style="background:#fffae0; color:darkgreen;">2.74</td>
<td style="text-align:center; background:#e0ffd8;">84.40</td>
<td style="background:#fffae0; border-left-width:2px; color:darkgreen;">0.24</td>
<td style="background:#fffae0; color:darkgreen;">2.33</td>
<td align="center"><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/Liechtenstein" title="Liechtenstein"><img alt="Liechtenstein" class="mw-file-element" data-file-height="600" data-file-width="1000" decoding="async" height="14" src="//upload.wikimedia.org/wikipedia/commons/thumb/4/47/Flag_of_Liechtenstein.svg/23px-Flag_of_Liechtenstein.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/4/47/Flag_of_Liechtenstein.svg/35px-Flag_of_Liechtenstein.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/4/47/Flag_of_Liechtenstein.svg/46px-Flag_of_Liechtenstein.svg.png 2x" width="23"/></a></span></span>
</td></tr>

In [32]:
# 'td' = table data, la celda

fila.find_all('td')[3]

In [33]:
fila.find_all('td')[3].text

'86.40'

In [34]:
float(fila.find_all('td')[3].text)

86.4

In [35]:
filas = cuerpo.find_all('tr')[3:]

In [36]:
data = []


for f in filas:
    
    tmp_lst = []
    
    casillas = f.find_all('td')
    
    for c in casillas:
        
        dato = c.text
        
        tmp_lst.append(dato)
        
    data.append(tmp_lst)

In [38]:
data[0]

['\xa0Liechtenstein',
 '84.40',
 '82.50',
 '86.40',
 '3.90',
 '76.83',
 '5.25',
 '82.07',
 '2.09',
 '84.16',
 '−2.50',
 '81.66',
 '2.74',
 '84.40',
 '0.24',
 '2.33',
 '\n']

In [39]:
import pandas as pd

In [40]:
df = pd.DataFrame(data)

df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,Liechtenstein,84.40,82.50,86.40,3.90,76.83,5.25,82.07,2.09,84.16,−2.50,81.66,2.74,84.40,0.24,2.33,\n
1,Switzerland,83.85,81.90,85.90,4.00,79.68,3.52,83.20,0.71,83.90,−0.90,83.00,0.85,83.85,−0.05,0.65,\n
2,Faroe Islands,83.50,81.40,85.70,4.30,78.44,3.16,81.59,1.35,82.95,0.25,83.20,0.30,83.50,0.55,1.90,\n
3,Spain,83.18,80.30,86.20,5.90,78.97,4.26,83.23,0.60,83.83,−1.50,82.33,0.85,83.18,−0.65,−0.05,\n
4,Norway,83.16,81.70,84.70,3.00,78.63,3.47,82.10,0.86,82.96,0.25,83.21,−0.05,83.16,0.20,1.06,\n
5,Sweden,83.16,81.40,85.00,3.60,79.64,2.61,82.25,0.86,83.11,−0.75,82.36,0.80,83.16,0.05,0.90,\n
6,Iceland,83.12,81.80,84.50,2.70,79.65,3.21,82.86,0.30,83.16,−0.10,83.06,0.05,83.12,−0.05,0.26,\n
7,Malta,82.86,81.30,84.50,3.20,78.35,3.70,82.05,0.81,82.86,−0.51,82.35,0.51,82.86,0.00,0.81,\n
8,Italy,82.80,80.60,85.10,4.50,79.78,3.31,83.09,0.41,83.50,−1.30,82.20,0.60,82.80,−0.70,−0.30,\n
9,Luxembourg,82.75,80.70,84.90,4.20,77.87,4.36,82.23,0.41,82.64,−0.50,82.14,0.60,82.75,0.11,0.52,\n
10,France,82.32,79.30,85.50,6.20,79.06,3.66,82.72,0.11,82.83,−0.65,82.18,0.15,82.32,−0.50,−0.40,\n
11,Ireland,82.10,80.20,84.10,3.90,76.54,4.81,81.35,1.35,82.70,−0.15,82.56,−0.45,82.10,−0.60,0.75,\n
12,Finland,81.93,79.30,84.70,5.40,77.47,3.71,81.18,0.80,81.98,−0.05,81.93,0.00,81.93,−0.05,0.75,\n
13,Belgium,81.89,79.50,84.40,4.90,77.72,3.57,81.29,0.71,82.00,−1.30,80.70,1.20,81.89,−0.10,0.60,\n
14,Netherlands,81.46,79.90,83.10,3.20,77.99,3.72,81.71,0.40,82.11,−0.75,81.36,0.10,81.46,−0.65,−0.25,\n
15,Denmark,81.40,79.60,83.30,3.70,76.59,4.11,80.70,0.75,81.45,0.15,81.60,−0.20,81.40,−0.05,0.70,\n
16,Austria,81.24,78.80,83.80,5.00,78.13,3.36,81.49,0.40,81.90,−0.70,81.19,0.05,81.24,−0.66,−0.25,\n
17,Channel Islands,81.23,79.11,83.36,4.24,79.16,2.73,81.88,−0.49,81.39,−0.13,81.26,−0.03,81.23,−0.16,−0.65,\n
18,Cyprus,81.20,79.21,83.20,3.99,76.57,4.20,80.77,0.63,81.40,−0.01,81.39,−0.19,81.20,−0.19,0.43,\n
19,Portugal,81.07,78.00,84.30,6.30,76.31,4.81,81.12,0.55,81.68,−0.70,80.98,0.10,81.07,−0.60,−0.05,\n
20,Germany,80.90,78.54,83.38,4.84,77.93,3.16,81.09,0.20,81.29,−0.25,81.04,−0.14,80.90,−0.39,−0.19,\n
21,Slovenia,80.88,77.90,84.00,6.10,75.41,5.67,81.08,0.45,81.53,−1.00,80.53,0.34,80.88,−0.65,−0.20,\n
22,United Kingdom,80.70,78.70,82.80,4.10,77.74,3.56,81.30,0.10,81.40,−1.05,80.35,0.35,80.70,−0.70,−0.60,\n
23,Isle of Man,80.53,78.56,82.53,3.97,74.72,5.31,80.04,0.70,80.74,−0.15,80.59,−0.06,80.53,−0.21,0.49,\n
24,Greece,80.18,77.50,83.00,5.50,77.89,3.50,81.39,0.25,81.64,−0.35,81.29,−1.10,80.18,−1.46,−1.20,\n
25,Gibraltar,79.33,77.11,81.70,4.59,81.37,0.51,81.88,0.48,82.36,−0.17,82.20,−2.87,79.33,−3.03,−2.55,\n
26,Czech Republic,77.37,74.30,80.60,6.30,74.97,3.86,78.82,0.40,79.23,−1.00,78.23,−0.85,77.37,−1.86,−1.45,\n
27,Estonia,76.74,72.40,81.30,8.90,70.42,6.62,77.03,1.61,78.65,−0.05,78.60,−1.85,76.74,−1.90,−0.29,\n
28,Albania,76.46,74.09,79.17,5.09,75.40,3.00,78.41,0.88,79.28,−2.29,76.99,−0.53,76.46,−2.82,−1.94,\n
29,Croatia,76.42,73.40,79.60,6.20,72.81,4.67,77.48,0.95,78.42,−0.70,77.72,−1.30,76.42,−2.00,−1.05,\n
30,Turkey,76.03,73.04,79.12,6.08,71.86,4.70,76.56,1.27,77.83,−1.98,75.85,0.18,76.03,−1.80,−0.53,\n
31,Poland,75.60,71.70,79.70,8.00,73.75,3.85,77.60,0.30,77.90,−1.40,76.50,−0.90,75.60,−2.30,−2.00,\n
32,Bosnia and Herzegovina,75.30,73.11,77.53,4.42,74.50,1.16,75.66,1.58,77.24,−1.02,76.22,−0.92,75.30,−1.94,−0.36,\n
33,Slovakia,74.71,71.30,78.30,7.00,73.05,3.76,76.81,0.85,77.67,−0.80,76.87,−2.15,74.71,−2.95,−2.10,\n
34,North Macedonia,74.54,72.41,76.77,4.36,72.95,2.50,75.45,1.15,76.60,−2.21,74.40,0.14,74.54,−2.07,−0.91,\n
35,Hungary,74.47,71.10,78.00,6.90,71.25,4.52,75.76,0.56,76.32,−0.75,75.57,−1.10,74.47,−1.85,−1.30,\n
36,Lithuania,74.34,69.90,79.00,9.10,72.02,2.50,74.52,1.77,76.28,−1.30,74.98,−0.64,74.34,−1.94,−0.18,\n
37,Montenegro,73.82,70.80,77.00,6.20,73.82,2.62,76.44,0.24,76.68,−0.75,75.93,−2.11,73.82,−2.86,−2.62,\n
38,Latvia,73.28,68.60,78.20,9.60,70.31,3.81,74.12,1.26,75.39,−0.20,75.19,−1.90,73.28,−2.10,−0.84,\n
39,Romania,72.96,69.40,76.70,7.30,71.16,3.75,74.91,0.70,75.61,−1.35,74.25,−1.29,72.96,−2.65,−1.95,\n
40,Serbia,72.73,69.96,75.64,5.68,71.58,3.75,75.34,0.60,75.94,−1.46,74.48,−1.75,72.73,−3.21,−2.61,\n
41,Belarus,72.37,67.30,77.70,10.40,68.91,4.06,72.97,1.26,74.23,−1.77,72.46,−0.09,72.37,−1.86,−0.60,\n
42,Armenia,72.04,66.55,77.35,10.80,70.62,3.43,74.06,1.38,75.44,−3.27,72.17,−0.13,72.04,−3.40,−2.02,\n
43,Georgia,71.69,66.80,76.68,9.88,69.58,3.52,73.10,0.37,73.47,−0.70,72.77,−1.07,71.69,−1.78,−1.41,\n
44,Bulgaria,71.51,68.10,75.10,7.00,71.66,2.80,74.47,0.65,75.11,−1.45,73.66,−2.14,71.51,−3.60,−2.95,\n
45,World,71.33,68.89,73.95,5.06,67.70,4.18,71.88,1.10,72.98,−0.74,72.24,−0.92,71.33,−1.65,−0.55,\n
46,Kazakhstan,70.23,66.33,74.03,7.70,65.45,5.99,71.44,1.74,73.18,−1.81,71.37,−1.14,70.23,−2.95,−1.21,\n
47,Ukraine,69.65,65.16,74.36,9.20,67.68,3.51,71.19,0.64,71.83,−0.64,71.19,−1.54,69.65,−2.18,−1.54,\n
48,Azerbaijan,69.37,65.65,73.29,7.64,64.89,6.22,71.12,1.99,73.10,−6.23,66.87,2.50,69.37,−3.74,−1.75,\n
49,Russia,69.36,64.21,74.77,10.56,65.48,5.26,70.74,2.34,73.08,−1.75,71.34,−1.98,69.36,−3.72,−1.38,\n
50,Moldova,68.85,64.44,73.55,9.10,66.42,2.61,69.03,1.90,70.94,−0.77,70.17,−1.32,68.85,−2.09,−0.19,\n

In [42]:
tablas = pd.read_html(url)

In [43]:
tablas[0]

   Countries & territories   2021                \
   Countries & territories    All   Male Female
0                      NaN    NaN    NaN    NaN
1            Liechtenstein  84.40  82.50  86.40
2              Switzerland  83.85  81.90  85.90
3            Faroe Islands  83.50  81.40  85.70
4                    Spain  83.18  80.30  86.20
5                   Norway  83.16  81.70  84.70
6                   Sweden  83.16  81.40  85.00
7                  Iceland  83.12  81.80  84.50
8                    Malta  82.86  81.30  84.50
9                    Italy  82.80  80.60  85.10
10              Luxembourg  82.75  80.70  84.90
11                  France  82.32  79.30  85.50
12                 Ireland  82.10  80.20  84.10
13                 Finland  81.93  79.30  84.70
14                 Belgium  81.89  79.50  84.40
15             Netherlands  81.46  79.90  83.10
16                 Denmark  81.40  79.60  83.30
17                 Austria  81.24  78.80  83.80
18         Channel Islands  81.23  79.11  83.36
19                  Cyprus  81.20  79.21  83.20
20                Portugal  81.07  78.00  84.30
21                 Germany  80.90  78.54  83.38
22                Slovenia  80.88  77.90  84.00
23          United Kingdom  80.70  78.70  82.80
24             Isle of Man  80.53  78.56  82.53
25                  Greece  80.18  77.50  83.00
26               Gibraltar  79.33  77.11  81.70
27          Czech Republic  77.37  74.30  80.60
28                 Estonia  76.74  72.40  81.30
29                 Albania  76.46  74.09  79.17
30                 Croatia  76.42  73.40  79.60
31                  Turkey  76.03  73.04  79.12
32                  Poland  75.60  71.70  79.70
33  Bosnia and Herzegovina  75.30  73.11  77.53
34                Slovakia  74.71  71.30  78.30
35         North Macedonia  74.54  72.41  76.77
36                 Hungary  74.47  71.10  78.00
37               Lithuania  74.34  69.90  79.00
38              Montenegro  73.82  70.80  77.00
39                  Latvia  73.28  68.60  78.20
40                 Romania  72.96  69.40  76.70
41                  Serbia  72.73  69.96  75.64
42                 Belarus  72.37  67.30  77.70
43                 Armenia  72.04  66.55  77.35
44                 Georgia  71.69  66.80  76.68
45                Bulgaria  71.51  68.10  75.10
46                   World  71.33  68.89  73.95
47              Kazakhstan  70.23  66.33  74.03
48                 Ukraine  69.65  65.16  74.36
49              Azerbaijan  69.37  65.65  73.29
50                  Russia  69.36  64.21  74.77
51                 Moldova  68.85  64.44  73.55

                                                                                   \
   .mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Sex gap
0                                                 NaN
1                                                3.90
2                                                4.00
3                                                4.30
4                                                5.90
5                                                3.00
6                                                3.60
7                                                2.70
8                                                3.20
9                                                4.50
10                                               4.20
11                                               6.20
12                                               3.90
13                                               5.40
14                                               4.90
15                                               3.20
16                                               3.70
17                                               5.00
18                                               4.24
19                                               3.99
20                                               6.30
21                                               4.84
22                                               6.10
23                                               4.10
24                                               3.97
25                                               5.50
26                                               4.59
27                                               6.30
28                                               8.90
29                                               5.09
30                                               6.20
31                                               6.08
32                                               8.00
33                                               4.42
34                                               7.00
35                                               4.36
36                                               6.90
37                                               9.10
38                                               6.20
39                                               9.60
40                                               7.30
41                                               5.68
42                                              10.40
43                                              10.80
44                                               9.88
45                                               7.00
46                                               5.06
47                                               7.70
48                                               9.20
49                                               7.64
50                                              10.56
51                                               9.10

   Historical data                                                        \
              2000 2000 →2014   2014 2014 →2019   2019 2019 →2020   2020
0              NaN        NaN    NaN        NaN    NaN        NaN    NaN
1            76.83       5.25  82.07       2.09  84.16      −2.50  81.66
2            79.68       3.52  83.20       0.71  83.90      −0.90  83.00
3            78.44       3.16  81.59       1.35  82.95       0.25  83.20
4            78.97       4.26  83.23       0.60  83.83      −1.50  82.33
5            78.63       3.47  82.10       0.86  82.96       0.25  83.21
6            79.64       2.61  82.25       0.86  83.11      −0.75  82.36
7            79.65       3.21  82.86       0.30  83.16      −0.10  83.06
8            78.35       3.70  82.05       0.81  82.86      −0.51  82.35
9            79.78       3.31  83.09       0.41  83.50      −1.30  82.20
10           77.87       4.36  82.23       0.41  82.64      −0.50  82.14
11           79.06       3.66  82.72       0.11  82.83      −0.65  82.18
12           76.54       4.81  81.35       1.35  82.70      −0.15  82.56
13           77.47       3.71  81.18       0.80  81.98      −0.05  81.93
14           77.72       3.57  81.29       0.71  82.00      −1.30  80.70
15           77.99       3.72  81.71       0.40  82.11      −0.75  81.36
16           76.59       4.11  80.70       0.75  81.45       0.15  81.60
17           78.13       3.36  81.49       0.40  81.90      −0.70  81.19
18           79.16       2.73  81.88      −0.49  81.39      −0.13  81.26
19           76.57       4.20  80.77       0.63  81.40      −0.01  81.39
20           76.31       4.81  81.12       0.55  81.68      −0.70  80.98
21           77.93       3.16  81.09       0.20  81.29      −0.25  81.04
22           75.41       5.67  81.08       0.45  81.53      −1.00  80.53
23           77.74       3.56  81.30       0.10  81.40      −1.05  80.35
24           74.72       5.31  80.04       0.70  80.74      −0.15  80.59
25           77.89       3.50  81.39       0.25  81.64      −0.35  81.29
26           81.37       0.51  81.88       0.48  82.36      −0.17  82.20
27           74.97       3.86  78.82       0.40  79.23      −1.00  78.23
28           70.42       6.62  77.03       1.61  78.65      −0.05  78.60
29           75.40       3.00  78.41       0.88  79.28      −2.29  76.99
30           72.81       4.67  77.48       0.95  78.42      −0.70  77.72
31           71.86       4.70  76.56       1.27  77.83      −1.98  75.85
32           73.75       3.85  77.60       0.30  77.90      −1.40  76.50
33           74.50       1.16  75.66       1.58  77.24      −1.02  76.22
34           73.05       3.76  76.81       0.85  77.67      −0.80  76.87
35           72.95       2.50  75.45       1.15  76.60      −2.21  74.40
36           71.25       4.52  75.76       0.56  76.32      −0.75  75.57
37           72.02       2.50  74.52       1.77  76.28      −1.30  74.98
38           73.82       2.62  76.44       0.24  76.68      −0.75  75.93
39           70.31       3.81  74.12       1.26  75.39      −0.20  75.19
40           71.16       3.75  74.91       0.70  75.61      −1.35  74.25
41           71.58       3.75  75.34       0.60  75.94      −1.46  74.48
42           68.91       4.06  72.97       1.26  74.23      −1.77  72.46
43           70.62       3.43  74.06       1.38  75.44      −3.27  72.17
44           69.58       3.52  73.10       0.37  73.47      −0.70  72.77
45           71.66       2.80  74.47       0.65  75.11      −1.45  73.66
46           67.70       4.18  71.88       1.10  72.98      −0.74  72.24
47           65.45       5.99  71.44       1.74  73.18      −1.81  71.37
48           67.68       3.51  71.19       0.64  71.83      −0.64  71.19
49           64.89       6.22  71.12       1.99  73.10      −6.23  66.87
50           65.48       5.26  70.74       2.34  73.08      −1.75  71.34
51           66.42       2.61  69.03       1.90  70.94      −0.77  70.17

                     COVID-19 impact            Unnamed: 16_level_0
   2020 →2021   2021      2019 →2021 2014 →2021 Unnamed: 16_level_1
0         NaN    NaN             NaN        NaN                 NaN
1        2.74  84.40            0.24       2.33                 NaN
2        0.85  83.85           −0.05       0.65                 NaN
3        0.30  83.50            0.55       1.90                 NaN
4        0.85  83.18           −0.65      −0.05                 NaN
5       −0.05  83.16            0.20       1.06                 NaN
6        0.80  83.16            0.05       0.90                 NaN
7        0.05  83.12           −0.05       0.26                 NaN
8        0.51  82.86            0.00       0.81                 NaN
9        0.60  82.80           −0.70      −0.30                 NaN
10       0.60  82.75            0.11       0.52                 NaN
11       0.15  82.32           −0.50      −0.40                 NaN
12      −0.45  82.10           −0.60       0.75                 NaN
13       0.00  81.93           −0.05       0.75                 NaN
14       1.20  81.89           −0.10       0.60                 NaN
15       0.10  81.46           −0.65      −0.25                 NaN
16      −0.20  81.40           −0.05       0.70                 NaN
17       0.05  81.24           −0.66      −0.25                 NaN
18      −0.03  81.23           −0.16      −0.65                 NaN
19      −0.19  81.20           −0.19       0.43                 NaN
20       0.10  81.07           −0.60      −0.05                 NaN
21      −0.14  80.90           −0.39      −0.19                 NaN
22       0.34  80.88           −0.65      −0.20                 NaN
23       0.35  80.70           −0.70      −0.60                 NaN
24      −0.06  80.53           −0.21       0.49                 NaN
25      −1.10  80.18           −1.46      −1.20                 NaN
26      −2.87  79.33           −3.03      −2.55                 NaN
27      −0.85  77.37           −1.86      −1.45                 NaN
28      −1.85  76.74           −1.90      −0.29                 NaN
29      −0.53  76.46           −2.82      −1.94                 NaN
30      −1.30  76.42           −2.00      −1.05                 NaN
31       0.18  76.03           −1.80      −0.53                 NaN
32      −0.90  75.60           −2.30      −2.00                 NaN
33      −0.92  75.30           −1.94      −0.36                 NaN
34      −2.15  74.71           −2.95      −2.10                 NaN
35       0.14  74.54           −2.07      −0.91                 NaN
36      −1.10  74.47           −1.85      −1.30                 NaN
37      −0.64  74.34           −1.94      −0.18                 NaN
38      −2.11  73.82           −2.86      −2.62                 NaN
39      −1.90  73.28           −2.10      −0.84                 NaN
40      −1.29  72.96           −2.65      −1.95                 NaN
41      −1.75  72.73           −3.21      −2.61                 NaN
42      −0.09  72.37           −1.86      −0.60                 NaN
43      −0.13  72.04           −3.40      −2.02                 NaN
44      −1.07  71.69           −1.78      −1.41                 NaN
45      −2.14  71.51           −3.60      −2.95                 NaN
46      −0.92  71.33           −1.65      −0.55                 NaN
47      −1.14  70.23           −2.95      −1.21                 NaN
48      −1.54  69.65           −2.18      −1.54                 NaN
49       2.50  69.37           −3.74      −1.75                 NaN
50      −1.98  69.36           −3.72      −1.38                 NaN
51      −1.32  68.85           −2.09      −0.19                 NaN

In [44]:
tablas[-1]

,0,1
0,Ages of consent Etiquette Social (and financia...,Ages of consent Etiquette Social (and financia...
1,Culture,Art painting sculpture Architecture Capital of...
2,Demographics,Ageing Childhood population (%) Ethnic groups ...

In [48]:
len(tablas)

14

In [49]:
tablas[2]

                 Countries Life expectancy at birth                          \
                 Countries                      All     M     F  FΔM Δ 2000
0                      NaN                      NaN   NaN   NaN  NaN    NaN
1              Switzerland                     83.4  81.8  85.1  3.3    3.7
2                    Spain                     83.2  80.7  85.7  5.0    4.1
3                   Cyprus                     83.1  81.1  85.1  4.0    4.4
4                    Italy                     83.0  80.9  84.9  4.0    3.6
5                   Norway                     82.6  81.1  84.1  3.0    4.1
6                   France                     82.5  79.8  85.1  5.3    3.6
7                   Sweden                     82.4  80.8  84.0  3.2    2.8
8               Luxembourg                     82.4  80.6  84.2  3.6    4.2
9                  Iceland                     82.3  80.8  83.9  3.1    2.6
10                   Malta                     81.9  79.9  83.8  3.9    4.0
11             Netherlands                     81.8  80.4  83.1  2.7    3.8
12                 Ireland                     81.8  80.2  83.5  3.3    5.4
13                 Germany                     81.7  78.7  84.8  6.1    3.6
14                Portugal                     81.6  78.6  84.4  5.8    5.0
15                 Finland                     81.6  79.2  84.0  4.8    4.0
16                 Austria                     81.6  79.4  83.8  4.4    3.4
17                 Belgium                     81.4  79.3  83.5  4.2    3.7
18          United Kingdom                     81.4  79.8  83.0  3.2    3.5
19                 Denmark                     81.3  79.6  83.0  3.4    4.4
20                Slovenia                     81.3  78.6  84.1  5.5    5.2
21                  Greece                     81.1  78.6  83.6  5.0    2.9
22          Czech Republic                     79.1  76.3  81.9  5.6    4.1
23                 Estonia                     78.9  74.7  82.6  7.9    8.0
24                 Croatia                     78.6  75.5  81.6  6.1    4.2
25                  Turkey                     78.6  76.4  80.7  4.3    4.2
26                  Poland                     78.3  74.5  81.9  7.4    4.6
27                Slovakia                     78.2  74.8  81.4  6.6    4.9
28               Europe[9]                     78.2  75.1  81.3  6.2    5.7
29                 Albania                     78.0  76.3  79.9  3.6    4.5
30  Bosnia and Herzegovina                     76.8  74.4  79.1  4.7    1.4
31                 Hungary                     76.4  73.1  79.6  6.5    5.1
32                 Armenia                     76.0  72.5  79.2  6.7    4.1
33               Lithuania                     76.0  71.2  80.4  9.2    4.0
34              Montenegro                     75.9  73.2  78.7  5.5    2.3
35                  Serbia                     75.9  73.5  78.3  4.8    4.5
36                 Romania                     75.6  72.0  79.3  7.3    4.2
37                  Latvia                     75.4  70.6  79.8  9.2    5.2
38                Bulgaria                     75.1  71.6  78.6  7.0    3.5
39         North Macedonia                     74.8  72.8  76.9  4.1    3.7
40                 Belarus                     74.8  69.7  79.6  9.9    6.0
41              Kazakhstan                     74.0  70.0  77.6  7.6   10.9
42                 Georgia                     73.3  68.8  77.8  9.0    3.9
43                 Moldova                     73.3  69.3  77.1  7.8    6.4
44                   World                     73.3  70.8  75.9  5.1    6.5
45                  Russia                     73.2  68.2  78.0  9.8    7.9
46                 Ukraine                     73.0  68.0  77.8  9.8    5.5
47              Azerbaijan                     71.4  68.8  74.1  5.3    5.9

   HALE at birth                   ... Life expectancy at age 60             \
             All     M     F  FΔM  ...                         M     F  FΔM
0            NaN   NaN   NaN  NaN  ...                       NaN   NaN  NaN
1           72.5  72.2  72.8  0.6  ...                      24.1  26.6  2.5
2           72.1  71.3  72.9  1.6  ...                      23.3  27.3  4.0
3           72.4  71.8  73.0  1.2  ...                      23.3  26.4  3.1
4           71.9  71.2  72.6  1.4  ...                      23.4  26.5  3.1
5           71.4  71.0  71.6  0.6  ...                      23.5  25.8  2.3
6           72.1  71.1  73.1  2.0  ...                      23.3  27.2  3.9
7           71.9  71.7  72.1  0.4  ...                      23.3  25.6  2.3
8           71.6  71.1  72.0  0.9  ...                      22.9  25.8  2.9
9           72.0  71.7  72.3  0.6  ...                      23.7  25.5  1.8
10          71.5  70.9  71.9  1.0  ...                      23.0  25.9  2.9
11          71.4  71.3  71.5  0.2  ...                      23.0  25.1  2.1
12          71.1  70.7  71.4  0.7  ...                      23.0  25.3  2.3
13          70.9  69.7  72.1  2.4  ...                      21.9  26.9  5.0
14          71.0  69.6  72.2  2.6  ...                      22.1  26.3  4.2
15          71.0  69.9  72.0  2.1  ...                      22.4  25.8  3.4
16          70.9  69.9  71.9  2.0  ...                      22.4  25.6  3.2
17          70.6  69.8  71.3  1.5  ...                      22.3  25.6  3.3
18          70.1  69.6  70.6  1.0  ...                      23.0  25.2  2.2
19          71.0  70.7  71.4  0.7  ...                      22.3  24.9  2.6
20          70.7  69.0  72.5  3.5  ...                      21.8  25.6  3.8
21          70.9  69.9  71.9  2.0  ...                      22.1  25.5  3.4
22          68.8  67.0  70.6  3.6  ...                      19.9  24.0  4.1
23          69.2  66.4  71.7  5.3  ...                      19.3  25.0  5.7
24          68.6  66.7  70.5  3.8  ...                      19.4  23.7  4.3
25          68.4  67.8  69.0  1.2  ...                      20.6  23.2  2.6
26          68.7  65.9  71.3  5.4  ...                      19.5  24.3  4.8
27          68.5  66.2  70.8  4.6  ...                      19.3  23.9  4.6
28          68.3  66.6  70.0  3.4  ...                      20.5  24.3  3.8
29          69.1  68.0  70.3  2.3  ...                      20.2  21.9  1.7
30          67.2  65.7  68.7  3.0  ...                      18.6  21.6  3.0
31          67.2  65.0  69.3  4.3  ...                      17.7  22.3  4.6
32          67.1  64.9  69.1  4.2  ...                      18.2  22.1  3.9
33          66.7  63.4  69.7  6.3  ...                      17.6  23.5  5.9
34          67.0  65.2  68.7  3.5  ...                      17.4  21.3  3.9
35          66.9  65.4  68.4  3.0  ...                      17.9  21.1  3.2
36          66.8  64.3  69.4  5.1  ...                      17.8  22.4  4.6
37          66.2  62.9  69.3  6.4  ...                      17.2  23.0  5.8
38          66.3  63.9  68.7  4.8  ...                      17.4  22.0  4.6
39          66.1  65.1  67.3  2.2  ...                      17.0  19.6  2.6
40          66.0  62.3  69.4  7.1  ...                      16.0  22.5  6.5
41          65.0  62.4  67.4  5.0  ...                      16.8  21.4  4.6
42          64.7  61.4  67.9  6.5  ...                      16.0  21.0  5.0
43          64.5  61.9  67.1  5.2  ...                      16.6  20.9  4.3
44          63.7  62.5  64.9  2.4  ...                      19.5  22.7  3.2
45          64.2  60.7  67.5  6.8  ...                      16.8  22.2  5.4
46          64.3  60.6  67.8  7.2  ...                      16.4  21.7  5.3
47          63.6  62.1  65.2  3.1  ...                      15.6  18.3  2.7

          HALE at age 60                         Unnamed: 21_level_0
   Δ 2000            All     M     F  FΔM Δ 2000 Unnamed: 21_level_1
0     NaN            NaN   NaN   NaN  NaN    NaN                 NaN
1     2.4           19.5  18.8  20.2  1.4    1.8                 NaN
2     2.7           19.2  18.0  20.3  2.3    1.9                 NaN
3     3.0           19.0  18.1  19.9  1.8    2.2                 NaN
4     2.5           18.9  17.9  19.8  1.9    1.8                 NaN
5     2.7           18.5  17.8  19.1  1.3    1.8                 NaN
6     2.3           19.7  18.5  20.8  2.3    1.7                 NaN
7     2.1           18.9  18.3  19.4  1.1    1.5                 NaN
8     2.6           18.5  17.7  19.3  1.6    1.8                 NaN
9     2.0           19.0  18.6  19.4  0.8    1.6                 NaN
10    3.7           18.9  18.0  19.6  1.6    2.7                 NaN
11    2.8           18.4  17.9  18.9  1.0    1.8                 NaN
12    4.0           18.6  18.0  19.2  1.2    2.9                 NaN
13    2.6           18.5  17.0  19.9  2.9    1.7                 NaN
14    3.1           18.6  17.3  19.8  2.5    2.3                 NaN
15    2.6           18.5  17.3  19.5  2.2    2.0                 NaN
16    2.1           18.3  17.2  19.4  2.2    1.6                 NaN
17    2.4           18.2  17.2  19.1  1.9    1.6                 NaN
18    2.8           18.3  17.6  18.9  1.3    2.0                 NaN
19    3.0           18.2  17.6  18.9  1.3    2.2                 NaN
20    3.3           17.8  16.4  19.2  2.8    2.5                 NaN
21    2.3           18.4  17.3  19.5  2.2    1.6                 NaN
22    2.8           16.3  14.7  17.8  3.1    1.7                 NaN
23    3.9           17.3  14.8  19.1  4.3    3.0                 NaN
24    2.8           16.2  14.6  17.7  3.1    1.8                 NaN
25    0.5           16.6  15.8  17.3  1.5    0.3                 NaN
26    2.9           16.8  14.9  18.5  3.6    2.1                 NaN
27    3.3           16.6  14.6  18.2  3.6    2.4                 NaN
28    2.9           17.1  15.8  18.3  2.5    2.1                 NaN
29    2.0           16.6  15.9  17.3  1.4    1.6                 NaN
30    0.6           15.2  14.1  16.2  2.1    0.2                 NaN
31    2.2           15.3  13.4  16.8  3.4    1.7                 NaN
32    1.6           15.7  14.2  16.9  2.7    1.2                 NaN
33    1.4           15.9  13.4  17.8  4.4    1.2                 NaN
34    0.2           14.9  13.5  16.3  2.8    0.0                 NaN
35    2.5           14.9  13.7  16.0  2.3    1.7                 NaN
36    2.1           15.7  13.8  17.3  3.5    1.6                 NaN
37    2.2           15.6  13.2  17.4  4.2    1.7                 NaN
38    2.2           15.2  13.4  16.9  3.5    1.5                 NaN
39    1.9           14.0  13.1  14.9  1.8    1.3                 NaN
40    2.5           15.1  12.3  17.2  4.9    2.0                 NaN
41    4.2           14.8  13.0  16.2  3.2    3.0                 NaN
42    1.8           14.4  12.4  16.1  3.7    1.0                 NaN
43    3.2           14.6  12.8  16.0  3.2    2.5                 NaN
44    2.3           15.8  14.8  16.6  1.8    1.7                 NaN
45    3.5           15.0  12.8  16.7  3.9    2.7                 NaN
46    2.7           15.0  12.7  16.7  4.0    2.2                 NaN
47    0.5           13.4  12.4  14.2  1.8    0.3                 NaN

[48 rows x 22 columns]

In [52]:
pd.read_clipboard()   # ctrl+v, tienes que hacer ctrl+c en la pagina primero

Empty DataFrame
Columns: [84.40, 82.50, 86.40, 3.90, 76.83, 5.25, 82.07, 2.09, 84.16, −2.50, 81.66, 2.74, 84.40.1, 0.24, 2.33]
Index: []

In [53]:
pd.read_clipboard()

Empty DataFrame
Columns: [pd.read_clipboard()]
Index: []

In [54]:
data = []


for f in filas:
    
    tmp_lst = []
    
    casillas = f.find_all('td')
    
    for c in casillas:
        
        dato = c.text
        
        tmp_lst.append(dato)
        
    data.append(tmp_lst)

In [57]:
data = [[c.text for c in f.find_all('td')] for f in sopa.find('tbody').find_all('tr')[3:]]

df = pd.DataFrame(data)

df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,Liechtenstein,84.40,82.50,86.40,3.90,76.83,5.25,82.07,2.09,84.16,−2.50,81.66,2.74,84.40,0.24,2.33,\n
1,Switzerland,83.85,81.90,85.90,4.00,79.68,3.52,83.20,0.71,83.90,−0.90,83.00,0.85,83.85,−0.05,0.65,\n
2,Faroe Islands,83.50,81.40,85.70,4.30,78.44,3.16,81.59,1.35,82.95,0.25,83.20,0.30,83.50,0.55,1.90,\n
3,Spain,83.18,80.30,86.20,5.90,78.97,4.26,83.23,0.60,83.83,−1.50,82.33,0.85,83.18,−0.65,−0.05,\n
4,Norway,83.16,81.70,84.70,3.00,78.63,3.47,82.10,0.86,82.96,0.25,83.21,−0.05,83.16,0.20,1.06,\n

## SkyScanner

In [58]:
url = 'https://www.skyscanner.es/transporte/vuelos/mad/bkkt/240223/240306/?adultsv2=1&cabinclass=economy&childrenv2=&inboundaltsenabled=false&outboundaltsenabled=false&preferdirects=false&ref=home&rtn=1'

url

'https://www.skyscanner.es/transporte/vuelos/mad/bkkt/240223/240306/?adultsv2=1&cabinclass=economy&childrenv2=&inboundaltsenabled=false&outboundaltsenabled=false&preferdirects=false&ref=home&rtn=1'

In [60]:
html = req.get(url).text  # pagina dinamica, con bs4 no se puede

html

'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="x-ua-compatible" content="ie=edge"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name="theme-color" content="#000000"><link rel="manifest" href="./manifest.json"><link rel="shortcut icon" href="./favicon.ico"><title>Skyscanner</title><link rel="icon" href="/favicon.ico"><script type="text/javascript">window.__pageLoadedTime=Date.now()</script><script defer="defer" src="./static/js/main.e1799ab6.js"></script><link href="./static/css/main.fe2900da.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>'

## NBA

In [64]:
html = req.get('https://es.global.nba.com/statistics/').text

html[1000:2000]

'*/\n(()=>{var e,t,r={234:(e,t,r)=>{"use strict";r.d(t,{P_:()=>m,Mt:()=>b,C5:()=>s,DL:()=>w,OP:()=>D,lF:()=>O,Yu:()=>E,Dg:()=>v,CX:()=>c,GE:()=>x,sU:()=>N});var n=r(8632),i=r(9567);const o={beacon:n.ce.beacon,errorBeacon:n.ce.errorBeacon,licenseKey:void 0,applicationID:void 0,sa:void 0,queueTime:void 0,applicationTime:void 0,ttGuid:void 0,user:void 0,account:void 0,product:void 0,extra:void 0,jsAttributes:{},userAttributes:void 0,atts:void 0,transactionName:void 0,tNamePlain:void 0},a={};function s(e){if(!e)throw new Error("All info objects require an agent identifier!");if(!a[e])throw new Error("Info for ".concat(e," was never set"));return a[e]}function c(e,t){if(!e)throw new Error("All info objects require an agent identifier!");a[e]=(0,i.D)(t,o);const r=(0,n.ek)(e);r&&(r.info=a[e])}const u=e=>{if(!e||"string"!=typeof e)return!1;try{document.createDocumentFragment().querySelector(e)}catch{return!1}return!0};var d=r(7056),l=r(50);const f="[data-nr-mask]",h=()=>{const e={mask_selector:"'

In [65]:
sopa = bs(html, 'html.parser')

In [66]:
sopa.find('table')

## Linkedin

In [68]:
html = req.get('https://www.linkedin.com/jobs/search/?currentJobId=3835669388&distance=25&geoId=105646813&keywords=An%C3%A1lisis%20de%20datos&origin=JOBS_HOME_KEYWORD_HISTORY&refresh=true').text

In [70]:
sopa = bs(html, 'html.parser')

In [91]:
trabajo = sopa.find_all('ul')[6]

In [93]:
type(trabajo)

bs4.element.Tag

In [105]:
#trabajo

In [97]:
# tag = 'span', class_="sr-only"

trabajo.find('span', class_="sr-only").text.strip()

'Analista de Datos Junior'

In [109]:
trabajo.find('span', {'class':"sr-only"}).text.strip()

'Analista de Datos Junior'

In [103]:
trabajo.find_all('a')[1].text.strip()

'Grupo TECDATA Engineering'

In [112]:
trabajo.find('span', class_="job-search-card__location").text.strip()

'Madrid, Community of Madrid, Spain'

In [116]:
trabajo.find('time').text.strip()   # text saca el contenido

'5 days ago'

In [118]:
trabajo.find('time').attrs   # saca las pegatinas

{'class': ['job-search-card__listdate'], 'datetime': '2024-02-16'}

In [119]:
trabajo.find('time').attrs['datetime']

'2024-02-16'

In [126]:
len(trabajo.find_all('li'))

60

In [125]:
len(trabajo.find_all('time'))

60

In [129]:
trabajo.find_all('li')[59]

<li>
<div class="base-card relative w-full hover:no-underline focus:no-underline base-card--link base-search-card base-search-card--link job-search-card" data-column="1" data-entity-urn="urn:li:jobPosting:3830007371" data-impression-id="jobs-search-desktop-59" data-reference-id="HDJ9C7DOmFHKl1KF0BadKw==" data-row="60" data-tracking-id="kXiAOhpvFYwh1SRmTsLfPQ==">
<a class="base-card__full-link absolute top-0 right-0 bottom-0 left-0 p-0 z-[2]" data-tracking-client-ingraph="" data-tracking-control-name="public_jobs_jserp-result_search-card" data-tracking-will-navigate="" href="https://es.linkedin.com/jobs/view/consultor-a-business-analyst-mercados-at-ntt-data-europe-latam-3830007371?position=60&amp;pageNum=0&amp;refId=HDJ9C7DOmFHKl1KF0BadKw%3D%3D&amp;trackingId=kXiAOhpvFYwh1SRmTsLfPQ%3D%3D&amp;trk=public_jobs_jserp-result_search-card">
<span class="sr-only">


        Consultor/a Business Analyst Mercados


          </span>
</a>
<div class="search-entity-media">
<img alt="" class="artdeco-entity-image artdeco-entity-image--square-4" data-delayed-url="https://media.licdn.com/dms/image/D4D0BAQEo24eTOerqHQ/company-logo_100_100/0/1698827156703/ntt_data_europe_latam_logo?e=2147483647&amp;v=beta&amp;t=SAbnkLYxfSm9WVQgve8SlCAQf6zj_gol5svRLVrCPaI" data-ghost-classes="artdeco-entity-image--ghost" data-ghost-url="https://static.licdn.com/aero-v1/sc/h/9a9u41thxt325ucfh5z8ga4m8"/>
</div>
<div class="base-search-card__info">
<h3 class="base-search-card__title">

        Consultor/a Business Analyst Mercados

          </h3>
<h4 class="base-search-card__subtitle">
<a class="hidden-nested-link" data-tracking-client-ingraph="" data-tracking-control-name="public_jobs_jserp-result_job-search-card-subtitle" data-tracking-will-navigate="" href="https://es.linkedin.com/company/ntt-data-europe-latam?trk=public_jobs_jserp-result_job-search-card-subtitle">
            NTT DATA Europe &amp; Latam
          </a>
</h4>
<!-- -->
<div class="base-search-card__metadata">
<span class="job-search-card__location">
            Greater Madrid Metropolitan Area
          </span>
<div class="job-posting-benefits text-sm">
<icon class="job-posting-benefits__icon" data-delayed-url="https://static.licdn.com/aero-v1/sc/h/3p1v0uhy7uq0cm5zdvzp4eo18" data-svg-class-name="job-posting-benefits__icon-svg"></icon>
<span class="job-posting-benefits__text">
          Actively Hiring
<!-- --> </span>
</div>
<time class="job-search-card__listdate" datetime="2024-02-14">


































      1 week ago

          </time>
<!-- -->
</div>
</div>
<!-- -->
</div>
</li>

## UFC

In [131]:
html = req.get('https://www.ufcespanol.com/rankings').text

html[3000:4000]

'd.push(function() {\n\n        // Start by defining breakpoints for this ad.\n      var mapping = googletag.sizeMapping()\n              .addSize([1024, 768], [1440, 200])\n              .addSize([0, 0], [320, 50])\n            .build();\n  \n      googletag.slots["rankings_leaderboard"] = googletag.defineSlot("/5458/zuffa.ufc/rankings", [1440, 200], "js-dfp-tag-rankings_leaderboard")\n  \n\n    .addService(googletag.pubads())\n\n  \n  \n  \n        // Apply size mapping when there are breakpoints.\n    .defineSizeMapping(mapping)\n    ;\n\n  });\n\n</script>\n<script type="text/javascript">\ngoogletag.cmd.push(function() {\n\n      googletag.pubads().enableAsyncRendering();\n        googletag.pubads().enableSingleRequest();\n        googletag.pubads().collapseEmptyDivs(true);\n      \n  googletag.enableServices();\n});\n\n</script>\n<link rel="icon" href="/sites/default/files/ufc_logo.png" type="image/png" />\n<script src="/sites/default/files/google_tag/primary/google_tag.script.js?s8sr27" defer></script>\n<script>wind'

In [132]:
sopa = bs(html, 'html.parser')

In [146]:
tabla = sopa.find_all('table')[2]

In [147]:
filas = tabla.find_all('tr')

filas[0]

<tr>
<td class="views-field views-field-weight-class-rank">1          </td>
<td class="views-field views-field-title"><a href="/athlete/merab-dvalishvili" hreflang="en">Merab Dvalishvili</a> </td>
<td class="views-field views-field-weight-class-rank-change"><span class="athlete-rankings--rank-change athlete-rankings--rank-increase">Rank aumentado por</span> 1          </td>
</tr>

In [148]:
rank = filas[0].find_all('td')[0].text.strip()

rank

'1'

In [152]:
nombre = filas[0].find_all('td')[1].text.strip()

nombre

'Merab Dvalishvili'

In [159]:
enlace = 'https://www.ufcespanol.com' + filas[0].find_all('td')[1].find('a').attrs['href']

enlace

'https://www.ufcespanol.com/athlete/merab-dvalishvili'

In [161]:
aumento = filas[0].find_all('td')[2].text.strip()

aumento

'Rank aumentado por 1'

In [162]:
data = []

for f in filas:
    
    dictio = {'rank': f.find_all('td')[0].text.strip(),
              'nombre': f.find_all('td')[1].text.strip(),
              'enlace': 'https://www.ufcespanol.com' + f.find_all('td')[1].find('a').attrs['href'],
              'aumento': f.find_all('td')[2].text.strip()
             }
    
    
    data.append(dictio)

In [163]:
pd.DataFrame(data)

,rank,nombre,enlace,aumento
0,1,Merab Dvalishvili,https://www.ufcespanol.com/athlete/merab-dvali...,Rank aumentado por 1
1,2,Aljamain Sterling,https://www.ufcespanol.com/athlete/aljamain-st...,Rank disminuido por 1
2,3,Cory Sandhagen,https://www.ufcespanol.com/athlete/cory-sandhagen,Rank aumentado por 1
3,4,Petr Yan,https://www.ufcespanol.com/athlete/petr-yan,Rank aumentado por 1
4,5,Marlon Vera,https://www.ufcespanol.com/athlete/marlon-vera,Rank aumentado por 1
5,6,Henry Cejudo,https://www.ufcespanol.com/athlete/henry-cejudo,Rank disminuido por 3
6,7,Song Yadong,https://www.ufcespanol.com/athlete/yadong-song,
7,8,Deiveson Figueiredo,https://www.ufcespanol.com/athlete/deiveson-fi...,
8,9,Rob Font,https://www.ufcespanol.com/athlete/rob-font,
9,10,Jonathan Martinez,https://www.ufcespanol.com/athlete/jonathan-ma...,
10,11,Dominick Cruz,https://www.ufcespanol.com/athlete/dominick-cruz,
11,12,Pedro Munhoz,https://www.ufcespanol.com/athlete/pedro-munhoz,
12,13,Umar Nurmagomedov,https://www.ufcespanol.com/athlete/umar-nurmag...,
13,14,Mario Bautista,https://www.ufcespanol.com/athlete/mario-bautista,
14,15,Ricky Simon,https://www.ufcespanol.com/athlete/ricky-simon,

## FBI Top Ten

In [166]:
url = 'https://www.fbi.gov/wanted/topten'

In [167]:
html = req.get(url).text

In [168]:
sopa = bs(html, 'html.parser')

In [170]:
sopa.find('p')

## Disney

In [171]:
url = 'https://en.wikipedia.org/wiki/Walt_Disney'

html = req.get(url).text

sopa = bs(html, 'html.parser')

In [179]:
sopa.find_all('img')[4]

<img alt="Extended-protected article" class="mw-file-element" data-file-height="512" data-file-width="512" decoding="async" height="20" src="//upload.wikimedia.org/wikipedia/en/thumb/8/8c/Extended-protection-shackle.svg/20px-Extended-protection-shackle.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/8/8c/Extended-protection-shackle.svg/30px-Extended-protection-shackle.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/8/8c/Extended-protection-shackle.svg/40px-Extended-protection-shackle.svg.png 2x" width="20"/>

In [181]:
sopa.find_all('img')[0].attrs['src']

'/static/images/icons/wikipedia.png'

In [183]:
[e.attrs['src'] for e in sopa.find_all('img')]

['/static/images/icons/wikipedia.png',
 '/static/images/mobile/copyright/wikipedia-wordmark-en.svg',
 '/static/images/mobile/copyright/wikipedia-tagline-en.svg',
 '//upload.wikimedia.org/wikipedia/en/thumb/e/e7/Cscr-featured.svg/20px-Cscr-featured.svg.png',
 '//upload.wikimedia.org/wikipedia/en/thumb/8/8c/Extended-protection-shackle.svg/20px-Extended-protection-shackle.svg.png',
 '//upload.wikimedia.org/wikipedia/commons/thumb/d/df/Walt_Disney_1946.JPG/220px-Walt_Disney_1946.JPG',
 '//upload.wikimedia.org/wikipedia/commons/thumb/8/87/Walt_Disney_1942_signature.svg/150px-Walt_Disney_1942_signature.svg.png',
 '//upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Walt_Disney_Birthplace_Exterior_Hermosa_Chicago_Illinois.jpg/220px-Walt_Disney_Birthplace_Exterior_Hermosa_Chicago_Illinois.jpg',
 '//upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Walt_Disney_envelope_ca._1921.jpg/220px-Walt_Disney_envelope_ca._1921.jpg',
 '//upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Walt_Disney_Snow_white_1937_trailer_screenshot_%2813%29.jpg/220px-Walt_Disney_Snow_white_1937_trailer_screenshot_%2813%29.jpg',
 '//upload.wikimedia.org/wikipedia/commons/thumb/1/15/Disney_drawing_goofy.jpg/170px-Disney_drawing_goofy.jpg',
 '//upload.wikimedia.org/wikipedia/commons/thumb/8/8c/WaltDisneyplansDisneylandDec1954.jpg/220px-WaltDisneyplansDisneylandDec1954.jpg',
 '//upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Walt_disney_portrait_right.jpg/170px-Walt_disney_portrait_right.jpg',
 '//upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Walt_Disney_Grave.JPG/170px-Walt_Disney_Grave.JPG',
 '//upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Nuvola_apps_kaboodle.svg/16px-Nuvola_apps_kaboodle.svg.png',
 '//upload.wikimedia.org/wikipedia/commons/thumb/1/13/DisneySchiphol1951.jpg/220px-DisneySchiphol1951.jpg',
 '//upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Disney1968.jpg/170px-Disney1968.jpg',
 '//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Disney_Oscar_1953_%28cropped%29.jpg/170px-Disney_Oscar_1953_%28cropped%29.jpg',
 '//upload.wikimedia.org/wikipedia/en/thumb/4/4a/Commons-logo.svg/20px-Commons-logo.svg.png',
 '//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Wikiquote-logo.svg/23px-Wikiquote-logo.svg.png',
 '//upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Wikisource-logo.svg/26px-Wikisource-logo.svg.png',
 '//upload.wikimedia.org/wikipedia/en/thumb/8/8a/OOjs_UI_icon_edit-ltr-progressive.svg/10px-OOjs_UI_icon_edit-ltr-progressive.svg.png',
 '//upload.wikimedia.org/wikipedia/en/thumb/8/8a/OOjs_UI_icon_edit-ltr-progressive.svg/10px-OOjs_UI_icon_edit-ltr-progressive.svg.png',
 '//upload.wikimedia.org/wikipedia/en/thumb/9/96/Symbol_category_class.svg/16px-Symbol_category_class.svg.png',
 '//upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Disneyland_Resort_logo.svg/135px-Disneyland_Resort_logo.svg.png',
 '//upload.wikimedia.org/wikipedia/commons/thumb/d/da/Animation_disc.svg/20px-Animation_disc.svg.png',
 '//upload.wikimedia.org/wikipedia/en/thumb/6/69/P_vip.svg/19px-P_vip.svg.png',
 '//upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Mickey_Mouse_colored_%28head%29.svg/20px-Mickey_Mouse_colored_%28head%29.svg.png',
 '//upload.wikimedia.org/wikipedia/en/thumb/e/e7/Video-x-generic.svg/19px-Video-x-generic.svg.png',
 '//upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Flag_of_Los_Angeles_County%2C_California.svg/21px-Flag_of_Los_Angeles_County%2C_California.svg.png',
 '//upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Blank_television_set.svg/21px-Blank_television_set.svg.png',
 '//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/21px-Flag_of_the_United_States.svg.png',
 '//upload.wikimedia.org/wikipedia/en/thumb/8/8a/OOjs_UI_icon_edit-ltr-progressive.svg/10px-OOjs_UI_icon_edit-ltr-progressive.svg.png',
 'https://login.wikimedia.org/wiki/Special:CentralAutoLogin/start?type=1x1',
 '/static/images/footer/wikimedia-button.png',
 '/static/images/footer/poweredby_mediawiki_88x31.png']